Fix NoSuchMethodError for getTypeInfo()
Load an icon image for audio files from app resources instead because
ContentResolver#getTypeInfo() is for API level >= 29.
And it includes size-fit ic_photo_library_light images also.

Bug: 159987488
Test: Manual

Change-Id: Ie8f766f148a30e105e598e4b7e6b1b22bccda6ae
Signed-off-by: Taesu Lee <taesu82.lee@samsung.com>
Signed-off-by: Sipun Ku Mahanta <sipunkumar85@gmail.com>